services:
  - type: web
    name: ml-service
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    repo: https://github.com/Parthsawant1298/ml-project-1745865352.git
    branch: main
    plan: free
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.7"  # Full patch version
      - key: MODEL_FILE
        value: best_model.pkl
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
